### ISSUE TITLE
API url not replaced in docker image `:latest` tag

### ISSUE THREAD

**Issue by martadinata666** [go-vikunja/vikunja#203]
The `run.sh` in docker image `:latest` tag fail to replace API_URL in index.html. The API_URL stay at `/api/v1`, vice versa in `:unstable` tag the API URL replaced correctly.
Compose file exact same:
```
version: "3.5"
services: 
  frontend:
    image: vikunja/frontend:latest
    ports:
      - 80:80
    environment:
      VIKUNJA_API_URL: http://192.168.0.22:3456/api/v1
    restart: unless-stopped

```

```
version: "3.5"
services: 
  frontend:
    image: vikunja/frontend:unstable
    ports:
      - 80:80
    environment:
      VIKUNJA_API_URL: http://192.168.0.22:3456/api/v1
    restart: unless-stopped

```
