### ISSUE TITLE
invalid_scope on OIDC Login with Authelia after upgrading from 0.23.0 to 0.24.0 (& 0.24.1)

### ISSUE THREAD

**Issue by FieldofClay** [go-vikunja/vikunja#294]
### Description

I have OIDC login configured with Authelia. This has been working fine until the upgrade to 0.24.x, when I have started getting an invalid_scope message when clicking the 'Login with Authelia' button. My configuration has not changed, on either Vikunja or Authelia and the Authelia version has remained the same. Downgrading to 0.23.0 resolves the issue.

Vikunja Config:
```
auth:
  local:
    enabled: false
  openid:
    enabled: true
    redirecturl: https://vikunja.mydomain.com/auth/openid/
    providers:
      - name: Authelia
        authurl: https://auth.mydomain.com
        logouturl:
        clientid: vikunja
        clientsecret: ###SECRET###
        scope: openid profile email
```

Relevant Authelia config:
```
identity_providers:
  oidc:
    jwks:
      - certificate_chain: |
          -----BEGIN CERTIFICATE-----
          #####################
          -----END CERTIFICATE-----
        key: |
          -----BEGIN PRIVATE KEY-----
          #####################
          -----END PRIVATE KEY-----
    hmac_secret: ###SECRET###
    cors:
      endpoints:
        - userinfo
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
        - https://vikunja.mydomain.com
    clients:
      - client_id: vikunja
        client_name: Vikunja
        client_secret: '###SECRET###'
        public: false
        authorization_policy: one_factor
        token_endpoint_auth_method: client_secret_post
        redirect_uris:
          - https://vikunja.mydomain.com/auth/openid/authelia
        scopes:
          - email
          - openid
          - profile
```

When attempting to login, this error appears in Authelia, indicating Vikunja is not sending a valid scope:
```
Jul 26 09:49:01 authelia authelia[26877]: time="2024-07-26T09:49:01+00:00" level=error msg="Authorization Request failed with error: The requested scope is invalid, unknown, or malformed. The OAuth 2.0 Client is not allowed to request scope 'undefined'." method=GET path=/api/oidc/authorization remote_ip="##IPV6##" stack="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_authorization.go:41           OpenIDConnectAuthorization\ngithub.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:114 handleRouter.NewHTTPToAutheliaHandlerAdaptor.func21\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54                            handleRouter.(*BridgeBuilder).Build.func16.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:91                           SecurityHeadersNoStore.func1\ngithub.com/valyala/fasthttp@v1.52.0/userdata.go:57                                           (*userData).Get\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30                           SecurityHeadersBase.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/cors.go:216                             handleRouter.(*CORSPolicy).Middleware.func22\ngithub.com/fasthttp/router@v1.5.0/router.go:441                                              (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14                       handleRouter.LogRequest.func40\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38                            RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.52.0/server.go:2374                                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.52.0/workerpool.go:224                                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.52.0/workerpool.go:196                                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1695                                                                     goexit"
```

### Vikunja Version

0.24.0

### Browser and version

Firefox, Chrome

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![image](https://github.com/user-attachments/assets/ccd43afd-85e1-4887-bc8c-a5dbd91cf1f7)
