### ISSUE TITLE
Todoist import error

### ISSUE THREAD

**Issue by mariomaz87** [go-vikunja/vikunja#344]
### Description

Hi, I'm trying to import my Todoist tasks but the import process stops after only two tasks (I have hundreds of them).
In the log I have: 

```
2024-11-01T14:13:27Z: ERROR	▶ 5db [creating structure] Error while creating structure: Bucket does not exist [BucketID: 22]

2024-11-01T14:13:27Z: ERROR	▶ 5dc [Migration] Migration 1 from todoist for user 1 failed. Error was: Bucket does not exist [BucketID: 22]
```

This is my docker compose:

```
version: '3'

services:
  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://todo.mariorasp.duckdns.org/
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: xxx
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: xxx
      VIKUNJA_MIGRATION_TODOIST_CLIENTID: xxx
      VIKUNJA_MIGRATION_TODOIST_CLIENTSECRET: xxxx
      VIKUNJA_MIGRATION_TODOIST_ENABLE: true
      VIKUNJA_MIGRATION_TODOIST_REDIRECTURL: https://todo.mariorasp.duckdns.org/migrate/todoist
    ports:
      - 3456:3456
    volumes:
      - /home/mario/vikunja/files:/app/vikunja/files
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: xxxxx
      MYSQL_DATABASE: vikunja
    volumes:
      - /home/mario/vikunja/db:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      interval: 2s
      start_period: 30s
```

Thanks!

### Vikunja Version

0.24.4

### Can you reproduce the bug on the Vikunja demo site?

No
