### ISSUE TITLE
Uploading attachements doens´t work

### ISSUE THREAD

**Issue by Japhys** [go-vikunja/vikunja#362]
### Description

I just installed Vikunja and I am a fan already! Very fast, very clean, yet very flexible because of the views and filters! 
There is one thing i can´t get to work and that is uploads. Once I select a file and hit upload for a second it looks like it is going to upload but nothing actually happens.

### Vikunja Version

0.24.5

### Browser and version

Firefox Min-001 1.0 and Chromium Versie 130.0.6723.58  for Mint

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

It does work on the demo site so I guess it has something to do wit my setup

Docker compose

version: '3.8'

```
services:
  vikunja:
    image: vikunja/vikunja:latest
    container_name: vikunja
    environment:
      - VIKUNJA_DATABASE_TYPE=postgres
      - VIKUNJA_DATABASE_HOST=db
      - VIKUNJA_DATABASE_PORT=5432
      - VIKUNJA_DATABASE_USER=johndoe
      - VIKUNJA_DATABASE_PASSWORD=K5tKwyKcKfrfserfser23
      - VIKUNJA_DATABASE_NAME=vikunja
      - VIKUNJA_SERVER_HOST=0.0.0.0
      - VIKUNJA_SERVER_PORT=3456
    ports:
      - "9191:3456"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: vikunja_db
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=K5tKwyKcKfrfserfser23
      - POSTGRES_DB=vikunja
    volumes:
      - /srv/vikunja/db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
```

I am using Nginx Proxy Manager and used the recommended settings. 

This is what I see in console

![2024-11-24_14-59](https://github.com/user-attachments/assets/99f43a48-b184-4922-9d62-9f003679e8bc)
