### ISSUE TITLE
OIDC not working with latest "unstable"

### ISSUE THREAD

**Issue by admin-ideentriebwerk** [go-vikunja/vikunja#379]
### Description

I updated from `0.24.5` to the latest `unstable` and now getting `2024-12-15T19:16:17Z: CRITICAL	▶ 0fa It looks like your openid configuration is in the wrong format. Please check the docs for the correct format.`

With `0.24.5` it is working.

This is my config:
```
auth:
  openid:    
    enabled: true
    redirecturl: "https://vikunja.xxxx.com/auth/openid/"
    providers:     
      - name: authentik
        authurl: "https://authentik.xxxx.com/application/o/vikunja/"
        logouturl: "https://authentik.xxxx.com/application/o/vikunja/end-session/"
        clientid: "xxxx"
        clientsecret: "xxxx"
        scope: openid profile email vikunja_scope
```

This is my `docker-compose`:
```
name: vikunja
services:
  cft-vikunja-xxxxxxxxxx-com:
    container_name: cft-vikunja-xxxxxxxxxx-com
    image: cloudflare/cloudflared:2024.11.1
    restart: always
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
    networks:
      - cft-vikunja-xxxxxxxxxx-com

  vikunja:
    image: vikunja/vikunja:0.24.5
    container_name: vikunja
    environment:
      VIKUNJA_SERVICE_JWTSECRET: $VIKUNJA_SERVICE_JWTSECRET
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.xxxxxxxxxx.com
      VIKUNJA_SERVICE_ENABLEREGISTRATION: false
      VIKUNJA_SERVICE_TIMEZONE: Europe/Vienna
      VIKUNJA_SERVICE_ENABLEPUBLICTEAMS: false
      VIKUNJA_SERVICE_ENABLEOPENIDTEAMUSERSEARCH: true
      VIKUNJA_DATABASE_HOST: vikunja-db
      VIKUNJA_DATABASE_PASSWORD: $VIKUNJA_DATABASE_PASSWORD
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_REDIS_ENABLED: 1
      VIKUNJA_REDIS_HOST: 'vikunja-redis:6379'
      VIKUNJA_CACHE_ENABLED: 1
      VIKUNJA_CACHE_TYPE: redis
      VIKUNJA_MAILER_ENABLED: true
      VIKUNJA_MAILER_HOST: smtp.gmail.com
      VIKUNJA_MAILER_PORT: 465
      VIKUNJA_MAILER_AUTHTYPE: plain
      VIKUNJA_MAILER_USERNAME: it-services@xxxxxxxxxx.com
      VIKUNJA_MAILER_PASSWORD: $VIKUNJA_MAILER_PASSWORD
      VIKUNJA_MAILER_FROMEMAIL: "it-services @ vikunja"
      VIKUNJA_MIGRATION_TRELLO_ENABLE: true
      VIKUNJA_MIGRATION_TRELLO_KEY: $VIKUNJA_MIGRATION_TRELLO_KEY
      VIKUNJA_BACKGROUNDS_PROVIDERS_UNSPLASH_ENABLED: true
      VIKUNJA_BACKGROUNDS_PROVIDERS_UNSPLASH_ACCESSTOKEN: $VIKUNJA_UNSPLASH_ACCESSTOKEN
      VIKUNJA_KEYVALUE_TYPE: redis
      VIKUNJA_AUTH_LOCAL_ENABLED: false
      VIKUNJA_DEFAULTSETTINGS_EMAIL_REMINDERS_ENABLED: true
      VIKUNJA_DEFAULTSETTINGS_DISCOVERABLE_BY_NAME: true
      VIKUNJA_DEFAULTSETTINGS_DISCOVERABLE_BY_EMAIL: true
      VIKUNJA_DEFAULTSETTINGS_OVERDUE_TASKS_REMINDERS_ENABLED: true
      VIKUNJA_DEFAULTSETTINGS_OVERDUE_TASKS_REMINDERS_TIME: "7:00"
      VIKUNJA_DEFAULTSETTINGS_DEFAULT_PROJECT_ID: 0
      VIKUNJA_DEFAULTSETTINGS_WEEK_START: 1
      VIKUNJA_DEFAULTSETTINGS_TIMEZONE: Europe/Vienna
      VIKUNJA_LOG_LEVEL: DEBUG
    volumes:
      - vikunja-files:/app/vikunja/files
      - vikunja-config:/etc/vikunja
    depends_on:
      - vikunja-db
      - vikunja-redis
    restart: always
    networks:
      - vikunja
      - cft-vikunja-xxxxxxxxxx-com

  vikunja-db:
    image: postgres:16.6
    container_name: vikunja-db
    environment:
      POSTGRES_DB: vikunja
      POSTGRES_USER: vikunja
      POSTGRES_PASSWORD: $VIKUNJA_DATABASE_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s    
    networks:
      - vikunja

  vikunja-redis:
    image: redis:7.4.1
    container_name: vikunja-redis
    networks:
      - vikunja

volumes:
  pg-data:
  vikunja-files:
  vikunja-config:

networks:
  vikunja:
    name: vikunja
  cft-vikunja-xxxxxxxxxx-com:
    name: cft-vikunja-xxxxxxxxxx-com
```

### Vikunja Version

unstable

### Can you reproduce the bug on the Vikunja demo site?

Please select

**Comment by admin-ideentriebwerk** [comment]
It looks like the config changed. With this config it works:

```
auth:
  openid:
    enabled: true
    redirecturl: https://vikunja.xxx.com/auth/openid/
    providers:
      authentik:
        name: authentik
        authurl: https://authentik.xxx.com/application/o/vikunja/
        logouturl: https://authentik.xxx.com/application/o/vikunja/end-session/
        clientid: "xxx"
        clientsecret: "xxx"
        scope: openid profile email vikunja_scope
```
