### ISSUE TITLE
Docker+Admin can't administer instance (e.g. reset a user's password)

### ISSUE THREAD

**Issue by violet4** [go-vikunja/vikunja#386]
## Docker+Admin can't administer instance (e.g. reset a user's password)

i have installed Vikunja using Docker. my partner created an account recently but forgot to save her credentials. as admin, i wanted to get her back into her account.

from a web search i ended up at https://community.vikunja.io/t/how-to-manage-users-in-self-hosted-instance/1062

the suggestion there is to use `vikunja users cli commands`.

```
root@msi:/home/violet# docker exec -it 195a9718f5f4 vikunja users
OCI runtime exec failed: exec failed: unable to start container process: exec: "vikunja": executable file not found in $PATH: unknown
```

it seems the container doesn't have the cli tools installed or that i can't figure out how to access them properly.

i can't get a shell/dash/bash in the container with any docker container user. it appears that the docker container is heavily stripped down, which is great for security, but from my perspective/understanding, has no mechanisms for administration in the UI or elsewhere.

v0.24.6

`docker-compose`

```yaml
services:  
  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_JWTSECRET: '...'
      VIKUNJA_SERVICE_PUBLICURL: ...
      # Note the default path is /app/vikunja/vikunja.db.
      # This config variable moves it to a different folder so you can use a volume and 
      # store the database file outside the container so state is persisted even if the container is destroyed.
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
    ports:
      - 3456:3456
    volumes:
      - /mnt/docker_drive/docker/vikunja/data:/app/vikunja/files
      - /mnt/docker_drive/docker/vikunja/db:/db
    restart: unless-stopped
```

docker image:

* `vikunja/vikunja:latest`
* `sha256:cec159e222f578ece7447b56cb451178b13da2903c403ef26bea00c30e42c30f`

### Vikunja Version

v0.24.6

### Can you reproduce the bug on the Vikunja demo site?

No
