### ISSUE TITLE
Unix socket configuration doesn't work

### ISSUE THREAD

**Issue by eirnym** [go-vikunja/vikunja#396]
### Description

NOTE: configuration below worked earlier (from few months ago, I haven's saved version, sorry) and server is working using TCP socket

I have configuration which runs vikunja service using unix sockets. Previously it worked like a charm, and currently, server doesn't respond at all. 

my `config.yaml` is following:

```yaml
service:
  unixsocket: /path/to/vikunja.example.com.sock
  unixsocketmode: 0o666
  publicurl: https://vikunja.example.com
  enableemailreminders: false
```

domain and TLS has been setup on nginx. Previously vikunja also responded when I've used curl:
```zsh
curl -X GET --unix-socket /path/to/vikunja.example.com.sock http://vikunja.example.com/
```

I've tried to enable full logging and put logging everywhere, but it doesn't worked 

### Vikunja Version

Vikunja version v0.24.1-713-debdcd4dd3

### Browser and version

Firefox, curl

### Can you reproduce the bug on the Vikunja demo site?

Please select

**Comment by kolaente** [comment]
What kind of error do you see?

**Comment by eirnym** [comment]
I see no error, curl/browser just waits for nothing and I see nothing in logs.

**Comment by eirnym** [comment]
To narrow down search I tried tags and found that `v0.24.6` works perfectly. Probably, something wrong happened since last release.

**Comment by eirnym** [comment]
full config with all logging and all important options set (most of them are default, but I've searched for a solution)

```yaml
---
service:
  unixsocket: /path/to/vikunja.example.com.sock
  unixsocketmode: 0o666
  publicurl: https://vikunja.example.com
  enableemailreminders: false
log:
  enabled: true
  level: DEBUG
  echo: stdout
  database: true
  databaselevel: DEBUG
  events: stdout
  eventslevel: DEBUG

ratelimit:
  enabled: false
sentry:
  enabled: false
typesense:
  enabled: false
redis:
  enabled: false
mailer:
  enabled: false
migration:
  todoist:
    enabled: false
  trello:
    enabled: false
  microsofttodo:
    enabled: false
auth:
  openid:
    enabled: false
metrics:
  enabled: false
autotls:
  enabled: false
```
