### ISSUE TITLE
OAuth error on server reload while it's disabled

### ISSUE THREAD

**Issue by eirnym** [go-vikunja/vikunja#397]
### Description

I see an error on openid connect every time I restart the server. I don't run server all the time and don't use any OAuth providers.

Steps to reproduce:
1. Log in
2. Do your stuff
3. Kill server
4. Run server
5. Reload page

Error: message I see on screen:

```
Wystąpił błąd:
can't access property "find", e.auth.openidConnect.providers is null

Sprawdź, czy adres URL interfejsu API jest poprawny.
```

<strike>
Message in logs:

```
ERROR	▶ 102 invalid character 'd' looking for beginning of value
```
</strike>

Config:

```yaml
---
service:
  unixsocket: /opt/local/www/vikunja.example.com.sock
  unixsocketmode: 0o666
  publicurl: https://vikunja.example.com
  enableemailreminders: false
log:
  enabled: true

ratelimit:
  enabled: false
sentry:
  enabled: false
typesense:
  enabled: false
redis:
  enabled: false
mailer:
  enabled: false
migration:
  todoist:
    enabled: false
  trello:
    enabled: false
  microsofttodo:
    enabled: false
auth:
  openid:
    enabled: false
metrics:
  enabled: false
autotls:
  enabled: false
```

### Vikunja Version

v0.24.1-718-b85befb86a

### Browser and version

Firefox

### Can you reproduce the bug on the Vikunja demo site?

Yes
