### ISSUE TITLE
OpenID documentation wrong / providers not working

### ISSUE THREAD

**Issue by regnerisch** [go-vikunja/vikunja#623]
### Description

I created a config.yml like described in the documentation: 

```yaml
auth:
  openid:
    enabled: true
    providers:
      pocketid:
        name: "Pocket ID"
        authurl: ".../authorize"
        clientid: "..."
        clientsecret: "..."
```
Also the code seems to support that (valid) yaml. But I always get an internal server error (https://my-domain.com/api/v1/info)

If I change the providers to an array instead of an object (which is not documented but shown in many examples) 
I do not get an error, but the `openid_providers` inside the API-info endpoint is an empty array. Which is also wrong. I am not able to sign up or login with my OIDC provider as the frontend just shows the normal login/sign up page. 

```yaml
auth:
  openid:
    enabled: true
    providers:
      - name: "Pocket ID"
         authurl: ".../authorize"
         clientid: "..."
         clientsecret: "..."
```

I'm pretty sure this is not intended. This need to be fixed inside the code and the documentation must be updated too. It sould be an array or an object and should be consistant between the config documentation and examples. 

### Vikunja Version

0.24.6

### Can you reproduce the bug on the Vikunja demo site?

No
