### ISSUE TITLE
iOS CalDAV works but breaks as soon as recurring task is created in Vikunja

### ISSUE THREAD

**Issue by harrystuart** [go-vikunja/vikunja#728]
### Description

Hello, Vikunja makes clear that iOS CalDAV is not strongly supported. Support, however, would enable many users to sync with iOS Reminders which would be an absolute godsend.

I have successfully connected to and used Vikunja CalDAV with iOS Reminders. However, as soon as I create a recurring task in Vikunja, CalDAV completely breaks.

Below is the self-contained experiment I ran:

1. `docker-compose up | tee vikunja.log`
2. Logged into web app using Test
3. Connected to CalDAV with iOS
4. Created Test Web Task 1 in web app
5. Test Web Task 1 displayed in iOS Reminders
6. Created Test iOS Task 1 in iOS Reminders
7. Test iOS Task 1 displayed in web app
8. Created Test Web Recurring Task 1 with daily recurrence since completion (and later added due tomorrow) in web app
9. Test Web Recurring Task 1 not displayed in iOS Reminders
10. Created Test Web Task 2 in web app
11. Test Web Task 2 not displayed in iOS Reminders
12. Created Test iOS Task 2 in iOS Reminders
13. Test iOS Task 2 displayed in web app
14. Deleted CalDAV account from iOS
15. Restarted iOS
16. Connected to CalDAV with iOS
17. No tasks displayed in iOS Reminders

My `docker-compose.yml` looks like so:

```yaml
vikunja:
  image: vikunja/vikunja
  environment:
    VIKUNJA_DATABASE_TYPE: sqlite
    VIKUNJA_SERVICE_PUBLICURL: https://vikunja.hstu.net
    VIKUNJA_LOG_LEVEL: DEBUG
    VIKUNJA_LOG_EVENTS: stdout
    VIKUNJA_LOG_EVENTSLEVEL: DEBUG
  ports:
    - 3456:3456
  volumes:
    - /storage/enc/docker/vikunja/files:/app/vikunja/files
    - /storage/enc/docker/vikunja/db:/db
```

I have attached the logs output. I would greatly appreciate some assistance in parsing these log files and trying to arrest the offending backend logic - I am not a Go dev but am happy to do what I can if pointed in the right direction.

[vikunja.log](https://github.com/user-attachments/files/20073487/vikunja.log)

### Vikunja Version

v0.24.6

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![Image](https://github.com/user-attachments/assets/c82c5fb2-3b19-45ad-a2c6-0d5c7bcdd7e4)
